name: Open PR Agent Review
description: Run the Open PR Agent to generate an AI-powered pull request review summary.
author: open-pr-agent
branding:
  icon: check-square
  color: purple

inputs:
  openai_base_url:
    description: OpenAI-compatible HTTPS endpoint hosting the review model.
    required: true
  openai_model:
    description: Model identifier passed to the OpenAI-compatible backend.
    required: true
  openai_api_key:
    description: API token for the OpenAI-compatible backend.
    required: true
  github_token:
    description: Token with `pull_requests:write` scope. Defaults to the workflow `GITHUB_TOKEN`.
    required: false
    default: ""
  working_directory:
    description: Relative path to the repository checkout containing `main.py`.
    required: false
    default: "."
  agent_args:
    description: Extra arguments passed to `main.py`.
    required: false
    default: ""
  agent_output_path:
    description: Location for the saved OpenHands review text.
    required: false
    default: openhands-review.md

runs:
  using: composite
  steps:
    - name: Validate configuration
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        OPENAI_BASE_URL: ${{ inputs.openai_base_url }}
        OPENAI_MODEL: ${{ inputs.openai_model }}
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}
      run: |
        set -euo pipefail
        missing=0
        for var in OPENAI_BASE_URL OPENAI_MODEL OPENAI_API_KEY; do
          if [ -z "${!var:-}" ]; then
            echo "$var is required but not provided." >&2
            missing=1
          fi
        done
        if [ "$missing" -ne 0 ]; then
          exit 1
        fi

    - name: Setup uv
      uses: astral-sh/setup-uv@v4

    - name: Run Open PR Agent
      id: run-agent
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        OPENAI_BASE_URL: ${{ inputs.openai_base_url }}
        OPENAI_MODEL: ${{ inputs.openai_model }}
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}
        INPUT_AGENT_ARGS: ${{ inputs.agent_args }}
        AGENT_OUTPUT_PATH: ${{ inputs.agent_output_path }}
      run: |
        set -euo pipefail
        echo "Running Open PR Agent (OpenHands backend)"
        EVENT_ARG=()
        if [ -n "${GITHUB_EVENT_PATH:-}" ]; then
          EVENT_ARG=(--event-path "$GITHUB_EVENT_PATH")
        fi

        OUTPUT_ARGS=(--output-path "$AGENT_OUTPUT_PATH")
        if [ -n "$INPUT_AGENT_ARGS" ]; then
          uv run main.py "${EVENT_ARG[@]}" "${OUTPUT_ARGS[@]}" $INPUT_AGENT_ARGS
        else
          uv run main.py "${EVENT_ARG[@]}" "${OUTPUT_ARGS[@]}"
        fi
        echo "Agent output written to $AGENT_OUTPUT_PATH"
        cat "$AGENT_OUTPUT_PATH"

    - name: Submit review comment
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        GH_TOKEN: ${{ inputs.github_token || github.token }}
        AGENT_OUTPUT_PATH: ${{ inputs.agent_output_path }}
      run: |
        set -euo pipefail
        if [ -z "${GITHUB_EVENT_PATH:-}" ] || [ -z "${GITHUB_REPOSITORY:-}" ]; then
          echo "This action must run inside a GitHub Actions workflow." >&2
          exit 1
        fi
        if [ -z "${GITHUB_EVENT_NAME:-}" ] || [ "${GITHUB_EVENT_NAME}" != "pull_request" ]; then
          echo "Open PR Agent must run on pull_request events to know which PR to review." >&2
          exit 1
        fi
        if [ -z "${GH_TOKEN:-}" ]; then
          echo "GH_TOKEN is required to submit the review (pass github_token input if needed)." >&2
          exit 1
        fi
        if ! command -v jq >/dev/null 2>&1; then
          echo "jq is required but was not found in PATH." >&2
          exit 1
        fi

        PULL_NUMBER="$(jq -r '.pull_request.number // empty' "$GITHUB_EVENT_PATH")"
        if [ -z "$PULL_NUMBER" ]; then
          echo "Unable to read pull request number from event payload." >&2
          exit 1
        fi

        PAYLOAD_FILE="$(mktemp)"
        jq -Rs --arg event "COMMENT" '{event: $event, body: .}' "$AGENT_OUTPUT_PATH" > "$PAYLOAD_FILE"

        gh api \
          "repos/${GITHUB_REPOSITORY}/pulls/${PULL_NUMBER}/reviews" \
          --input "$PAYLOAD_FILE"
